provider:
  name: faas
  gateway: http://localhost:8080

functions:
  mma-stats:
    lang: node
    handler: ./mma-stats
    image: ericstoekl/mma-stats

  node-eval:
    lang: node
    handler: ./node-eval
    image: ericstoekl/node-eval

